server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8009/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://localhost:8011/
          predicates:
            - Path=/clients/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
