server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8009/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://localhost:8011/
          predicates:
            - Path=/clients/**

        - id: account-service
          uri: http://localhost:8012/
          predicates:
            - Path=/accounts/**

        - id: assignment-service
          uri: http://localhost:8013/
          predicates:
            - Path=/assignments/**

        - id: credit-service
          uri: http://localhost:8014/
          predicates:
            - Path=/credits/**

        - id: yanki-service
          uri: http://localhost:8015/
          predicates:
            - Path=/yanki/**

        - id: bootcoin-service
          uri: http://localhost:8016/
          predicates:
            - Path=/bootcoin/**